<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_64e3989e1255d',
    'title' => __('Lottie Files', 'modularity-lottie-files'),
    'fields' => array(
        0 => array(
            'key' => 'field_64e3989e13aac',
            'label' => __('Embed url', 'modularity-lottie-files'),
            'name' => 'mod_lottie_files_embed_url',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        1 => array(
            'key' => 'field_64e3a4d599ac4',
            'label' => __('Width', 'modularity-lottie-files'),
            'name' => 'mod_lottie_files_width',
            'type' => 'number',
            'instructions' => __('Width of the animation in %', 'modularity-lottie-files'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'min' => '',
            'max' => '',
            'placeholder' => '',
            'step' => '',
            'prepend' => '',
            'append' => '',
        ),
        2 => array(
            'key' => 'field_64e6622ec7a78',
            'label' => __('Position', 'modularity-lottie-files'),
            'name' => 'mod_lottie_files_position',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'left' => __('Left', 'modularity-lottie-files'),
                'center' => __('Center', 'modularity-lottie-files'),
                'right' => __('Right', 'modularity-lottie-files'),
            ),
            'default_value' => __('left', 'modularity-lottie-files'),
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        3 => array(
            'key' => 'field_64e50d4101074',
            'label' => __('Loop', 'modularity-lottie-files'),
            'name' => 'mod_lottie_files_loop',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        4 => array(
            'key' => 'field_64e50e8d01075',
            'label' => __('Controls', 'modularity-lottie-files'),
            'name' => 'mod_lottie_files_controls',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        5 => array(
            'key' => 'field_64e50ee201076',
            'label' => __('Autoplay', 'modularity-lottie-files'),
            'name' => 'mod_lottie_files_autoplay',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        6 => array(
            'key' => 'field_64e65f05be1e5',
            'label' => __('Background color', 'modularity-lottie-files'),
            'name' => 'mod_lottie_files_background_color',
            'type' => 'color_picker',
            'instructions' => __('This will add a background behind the animation', 'modularity-lottie-files'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => __('rgba(255,255,255,0)', 'modularity-lottie-files'),
            'enable_opacity' => 1,
            'return_format' => 'string',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-lottie-files',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/lottie-files',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}